package com.dfpt.canonical.service;

import com.dfpt.canonical.dto.ExternalTradeDTO;
import com.dfpt.canonical.model.CanonicalTrade;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Maps external DTOs to canonical trade entities
 * Handles date parsing in ddMMyyyyHHmmss format (e.g., 21012025143000)
 */
@Service
public class MapperService {

    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("ddMMyyyy");
    private static final DateTimeFormatter DATETIME_FORMATTER = DateTimeFormatter.ofPattern("ddMMyyyyHHmmss");

    public CanonicalTrade mapFromJson(ExternalTradeDTO dto) {
        CanonicalTrade trade = new CanonicalTrade();
        // ID will be auto-generated by database
        
        // Map all fields
        trade.setOriginatorType(convertOriginatorType(dto.getOriginatorType()));
        trade.setFirmNumber(dto.getFirmNumber());
        trade.setFundNumber(dto.getFundNumber());
        trade.setTransactionType(dto.getTransactionType());
        trade.setTransactionId(dto.getTransactionId());
        trade.setDollarAmount(dto.getDollarAmount());
        trade.setClientAccountNo(dto.getClientAccountNo());
        trade.setClientName(dto.getClientName());
        trade.setSsn(dto.getSsn());
        trade.setShareQuantity(dto.getShareQuantity());
        
        // Parse dates
        trade.setTradeDateTime(parseDateTime(dto.getTradeDateTime()));
        trade.setDob(parseDate(dto.getDob()));
        
        // Set metadata
        trade.setStatus("RECEIVED");
        trade.setCreatedAt(LocalDateTime.now());
        
        return trade;
    }
    
    private Date parseDate(String dateStr) {
        if (dateStr == null || dateStr.isEmpty()) {
            return null;
        }
        
        try {
            return LocalDate.parse(dateStr, DATE_FORMAT);
        } catch (Exception e) {
            return null;
        }
    }
    
    /**
     * Parse datetime string in ddMMyyyyHHmmss format
     */
    private LocalDateTime parseDateTime(String dateTimeStr) {
        if (dateTimeStr == null || dateTimeStr.isEmpty()) {
            return null;
        }
        
        try {
            return LocalDateTime.parse(dateTimeStr, DATETIME_FORMAT);
        } catch (Exception e) {
            return null;
        }
    }
    
    /**
     * Convert originator type from String to Integer
     * I (Internal) -> 1
     * E (External) -> 0
     */
    private Integer convertOriginatorType(String originatorType) {
        if (originatorType == null || originatorType.isEmpty()) {
            return null;
        }
        return "I".equalsIgnoreCase(originatorType) ? 1 : 0;
    }
}
